name: CI
on:
  push:
    branches:
      # Change this if your primary branch is not main
      - main
  pull_request:

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
        # setup pnpm
      - uses: pnpm/action-setup@v3
        with:
          version: 9.4.0
      - name: Restore cached npm dependencies
        uses: actions/cache/restore@v3
        with:
          path: |
            node_modules
          key: npm-dependencies-${{ hashFiles('pnpm-lock.yaml') }}
      - name: Print current dir content
        run: ls
      - run: pnpm install --frozen-lockfile
      - name: Cache npm dependencies
        uses: actions/cache/save@v3
        with:
          path: |
            node_modules
          key: npm-dependencies-${{ hashFiles('pnpm-lock.yaml') }}
      - uses: nrwl/nx-set-shas@v3
      # This line is needed for nx affected to work when CI is running on a PR
      - run: git branch --track main origin/main
        if: ${{ github.event_name == 'pull_request' }}
      - run: pnpm nx affected -t lint build test typecheck --parallel=4
